In [5]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install scikit-learn
!pip install joblib
!pip install jupyter

Requirement already satisfied: numpy in /home/ash/pygame_310/lib/python3.10/site-packages (2.2.6)
Requirement already satisfied: pandas in /home/ash/pygame_310/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /home/ash/pygame_310/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ash/pygame_310/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/ash/pygame_310/lib/python3.10/site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /home/ash/pygame_310/lib/python3.10/site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /home/ash/pygame_310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /home/ash/pygame_310/lib/python3.10/site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in /home/ash/pygame_310/lib/python3.10/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /home/ash/pygame_310/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/ash/pygame_310/lib/python3.10/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /home/ash/pygame_310/lib/python3.10/site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /home/ash/pygame_310/lib/python3.10/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /home/ash/pygame_310/lib/python3.10/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/ash/pygame_310/lib/python3.10/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/ash/pygame_310/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: scikit-learn in /home/ash/pygame_310/lib/python3.10/site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.8.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: joblib in /home/ash/pygame_310/lib/python3.10/site-packages (1.5.3)
Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting notebook (from jupyter)
  Downloading notebook-7.6.2-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting nbconvert (from jupyter)
  Downloading nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: ipykernel in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyter) (7.3.0)
Collecting ipywidgets (from jupyter)
  Downloading ipywidgets-8.1.9-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyterlab (from jupyter)
  Downloading jupyterlab-4.6.3-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: comm>=0.1.1 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (8.39.0)
Requirement already satisfied: jupyter-client>=8.9.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (8.9.1)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (1.7.2)
Requirement already satisfied: packaging>=22 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (26.2)
Requirement already satisfied: psutil>=5.7 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: pyzmq>=25 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (6.5.7)
Requirement already satisfied: traitlets>=5.4.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipykernel->jupyter) (5.15.1)
Requirement already satisfied: decorator in /home/ash/pygame_310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.3.1)
Requirement already satisfied: exceptiongroup in /home/ash/pygame_310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.3.1)
Requirement already satisfied: jedi>=0.16 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.20.0)
Requirement already satisfied: pexpect>4.3 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.20.0)
Requirement already satisfied: stack_data in /home/ash/pygame_310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /home/ash/pygame_310/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (4.16.0)
Requirement already satisfied: wcwidth in /home/ash/pygame_310/lib/python3.10/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.8.1)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /home/ash/pygame_310/lib/python3.10/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyter-client>=8.9.0->ipykernel->jupyter) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.10.0)
Requirement already satisfied: ptyprocess>=0.5 in /home/ash/pygame_310/lib/python3.10/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel->jupyter) (0.7.0)
Requirement already satisfied: six>=1.5 in /home/ash/pygame_310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.9.0->ipykernel->jupyter) (1.17.0)
Collecting widgetsnbextension~=4.0.16 (from ipywidgets->jupyter)
  Downloading widgetsnbextension-4.0.16-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.17 (from ipywidgets->jupyter)
  Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl.metadata (20 kB)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter)
  Downloading async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: httpx<1,>=0.25.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyterlab->jupyter) (3.1.6)
Collecting jupyter-builder>=1.0.2 (from jupyterlab->jupyter)
  Downloading jupyter_builder-1.2.3-py3-none-any.whl.metadata (7.8 kB)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter)
  Downloading jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.19.0 (from jupyterlab->jupyter)
  Downloading jupyter_server-2.21.1-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from jupyterlab->jupyter)
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting notebook-shim>=0.2 (from jupyterlab->jupyter)
  Downloading notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: tomli>=1.2.2 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyterlab->jupyter) (2.0.2)
Requirement already satisfied: anyio in /home/ash/pygame_310/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.14.0)
Requirement already satisfied: certifi in /home/ash/pygame_310/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /home/ash/pygame_310/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in /home/ash/pygame_310/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.18)
Requirement already satisfied: h11>=0.16 in /home/ash/pygame_310/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading jupyter_events-0.12.1-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading nbformat-5.11.1-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: overrides>=5.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (7.7.0)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading prometheus_client-0.26.0-py3-none-any.whl.metadata (2.1 kB)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: websocket-client>=1.7 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.9.0)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: json5>=0.9.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.10.0)
Requirement already satisfied: jsonschema>=4.18.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (4.26.0)
Requirement already satisfied: requests>=2.31 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.34.2)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading argon2_cffi_bindings-26.1.0-cp310-abi3-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (7.5 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/ash/pygame_310/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/ash/pygame_310/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.30.0)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading python_json_logger-4.2.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: pyyaml>=5.3 in /home/ash/pygame_310/lib/python3.10/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (6.0.3)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jsonpointer>1.13 in /home/ash/pygame_310/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.1.1)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting beautifulsoup4 (from nbconvert->jupyter)
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading bleach-6.4.0-py3-none-any.whl.metadata (32 kB)
Collecting defusedxml (from nbconvert->jupyter)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert->jupyter)
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert->jupyter)
  Downloading mistune-3.3.4-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert->jupyter)
  Downloading nbclient-0.11.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading webencodings-0.6.1-py3-none-any.whl.metadata (3.4 kB)
Collecting tinycss2>=1.1.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Downloading tinycss2-1.5.1-py3-none-any.whl.metadata (3.0 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading fastjsonschema-2.22.2-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ash/pygame_310/lib/python3.10/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /home/ash/pygame_310/lib/python3.10/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.7.0)
Requirement already satisfied: lark>=1.2.2 in /home/ash/pygame_310/lib/python3.10/site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: cffi>=1.0.1 in /home/ash/pygame_310/lib/python3.10/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.0.0)
Requirement already satisfied: pycparser in /home/ash/pygame_310/lib/python3.10/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert->jupyter)
  Downloading soupsieve-2.9.2-py3-none-any.whl.metadata (4.6 kB)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter)
  Downloading arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: tzdata in /home/ash/pygame_310/lib/python3.10/site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2026.2)
Requirement already satisfied: executing>=1.2.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/ash/pygame_310/lib/python3.10/site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (3.0.1)
Requirement already satisfied: pure-eval in /home/ash/pygame_310/lib/python3.10/site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Downloading jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Downloading ipywidgets-8.1.9-py3-none-any.whl (140 kB)
Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl (217 kB)
Downloading widgetsnbextension-4.0.16-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 13.6 MB/s  0:00:00
Downloading jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Downloading jupyterlab-4.6.3-py3-none-any.whl (17.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 13.8 MB/s  0:00:01m0:00:0100:01
Downloading jupyter_server-2.21.1-py3-none-any.whl (394 kB)
Downloading jupyterlab_server-2.28.0-py3-none-any.whl (59 kB)
Downloading argon2_cffi-25.1.0-py3-none-any.whl (14 kB)
Downloading async_lru-2.3.0-py3-none-any.whl (8.4 kB)
Downloading babel-2.18.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 13.8 MB/s  0:00:00eta 0:00:01
Downloading jupyter_builder-1.2.3-py3-none-any.whl (947 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 947.5/947.5 kB 14.8 MB/s  0:00:00
Downloading jupyter_events-0.12.1-py3-none-any.whl (19 kB)
Downloading jupyter_lsp-2.3.1-py3-none-any.whl (77 kB)
Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl (13 kB)
Downloading nbconvert-7.17.1-py3-none-any.whl (261 kB)
Downloading mistune-3.3.4-py3-none-any.whl (66 kB)
Downloading bleach-6.4.0-py3-none-any.whl (165 kB)
Downloading nbclient-0.11.0-py3-none-any.whl (25 kB)
Downloading nbformat-5.11.1-py3-none-any.whl (79 kB)
Downloading fastjsonschema-2.22.2-py3-none-any.whl (27 kB)
Downloading notebook_shim-0.2.4-py3-none-any.whl (13 kB)
Downloading pandocfilters-1.5.1-py2.py3-none-any.whl (8.7 kB)

In [9]:
import pandas as pd
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [10]:
DATA_PATH = "/home/ash/Projects/BMS/SpamProbabilityEngine/data/sms+spam+collection/SMSSpamCollection"
df = pd.read_csv(
    DATA_PATH,
    sep="\t",
    header=None,
    names=["label","message"]
)

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
print(df.head())

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
print("Number of messages:", len(df))

print("\nLabels:")
print(df["label"].value_counts())

print("\nMissing values:")
print(df.isnull().sum())

Number of messages: 5572

Labels:
label
ham     4825
spam     747
Name: count, dtype: int64

Missing values:
label      0
message    0
dtype: int64

In [13]:
df["target"] = df["label"].map({
    "ham": 0,
    "spam": 1
})

df.head()

  label                                            message  target
0   ham  Go until jurong point, crazy.. Available only ...       0
1   ham                      Ok lar... Joking wif u oni...       0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...       1
3   ham  U dun say so early hor... U c already then say...       0
4   ham  Nah I don't think he goes to usf, he lives aro...       0

In [14]:
X = df["message"]
y = df["target"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [16]:
vectorizer = CountVectorizer()

X_train_vectorized = vectorizer.fit_transform(X_train)

X_test_vectorized = vectorizer.transform(X_test)

In [19]:

print(vectorizer.get_feature_names_out()[:30])

['00' '000' '000pes' '008704050406' '0089' '0121' '01223585236'
 '01223585334' '02' '0207' '02072069400' '02073162414' '02085076972' '021'
 '03' '04' '0430' '05' '050703' '0578' '06' '07' '07008009200'
 '07046744435' '07090298926' '07099833605' '07123456789' '0721072'
 '07732584351' '07734396839']

In [20]:
model = MultinomialNB()

model.fit(
    X_train_vectorized,
    y_train
)

MultinomialNB()

In [24]:
message = ["Congratulations! You won an iphone!"]

message_vector = vectorizer.transform(message)

prediction = model.predict(message_vector)

print(prediction)

[1]

In [25]:
probability = model.predict_proba(message_vector)

print(probability)

[[0.06689555 0.93310445]]

In [26]:
print(
    f"Spam probability: {probability[0][1]:.2%}"
)

Spam probability: 93.31%

In [36]:
def check_message(message):

    message_vector = vectorizer.transform([message])

    prediction = model.predict(message_vector)[0]

    probability = model.predict_proba(
        message_vector
    )[0][1]

    if prediction == 1:
        result = "SPAM"
    else:
        result = "NOT SPAM"

    print("Message:", message)
    print("Prediction:", result)
    print(
        f"Spam probability: {probability:.2%}"
    )

In [40]:
message = input("Enter a message: ")

check_message(message)

Message: Where are you?
Prediction: NOT SPAM
Spam probability: 0.27%

In [41]:
y_pred = model.predict(
    X_test_vectorized
)

accuracy = accuracy_score(
    y_test,
    y_pred
)

print(
    f"Accuracy: {accuracy:.2%}"
)

Accuracy: 99.19%

In [42]:
print(
    classification_report(
        y_test,
        y_pred,
        target_names=["Ham", "Spam"]
    )
)

              precision    recall  f1-score   support

         Ham       0.99      1.00      1.00       966
        Spam       1.00      0.94      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [43]:
messages = [
    "Congratulations! You won a free prize!",
    "Hey, are you coming to class tomorrow?",
    "URGENT! Claim your reward now!",
    "Can you send me the project file?",
    "FREE money waiting for you!"
]

for message in messages:

    check_message(message)
    print("-" * 50)

Message: Congratulations! You won a free prize!
Prediction: SPAM
Spam probability: 100.00%
--------------------------------------------------
Message: Hey, are you coming to class tomorrow?
Prediction: NOT SPAM
Spam probability: 0.00%
--------------------------------------------------
Message: URGENT! Claim your reward now!
Prediction: SPAM
Spam probability: 100.00%
--------------------------------------------------
Message: Can you send me the project file?
Prediction: NOT SPAM
Spam probability: 0.03%
--------------------------------------------------
Message: FREE money waiting for you!
Prediction: NOT SPAM
Spam probability: 16.04%
--------------------------------------------------